version: 2
jobs:
  build:
    branches:
      only:
        - master
    docker:
      - image: buildpack-deps:trusty
    steps:
      - checkout
      - deploy:
          name: Deploy master to Heroku
          command: |
            git push https://heroku:$HEROKU_API_KEY@git.heroku.com/$HEROKU_APP_NAME.git master